---
- name: Execute logic across all managed clusters
  hosts: localhost
  vars:
    generated_sa_name: "{{ aap_sa_name | default('aap-sa') }}"
  tasks:
    - name: Assert that hub_url and hub_token vars are defined
      ansible.builtin.assert:
        that:
          - hub_url is defined
          - hub_token is defined
        quiet: true

    - name: Managed Cluster List Retrieval Tasks
      ansible.builtin.include_tasks: ./tasks/managed_cluster_list_retrieval.yml

    - name: Logic Block
      when: clusters | length > 0
      block:
        - name: K8S Tokens Generation Tasks
          ansible.builtin.include_tasks: ./tasks/k8s_tokens_generation.yml
          loop: "{{ clusters }}"
          vars:
            cluster_name: "{{ item }}"

        - name: Logic Execution Tasks
          ansible.builtin.include_tasks: ./tasks/logic/sa_count_per_scc.yml
          loop: "{{ clusters }}"
          vars:
            cluster_name: "{{ item }}"
      always:
        - name: Cleanup Tasks
          ansible.builtin.include_tasks: ./tasks/cleanup.yml
          loop: "{{ clusters }}"
          vars:
            cluster_name: "{{ item }}"
