- name: Delete ManagedServiceAccount - cluster {{ cluster.name }}
  kubernetes.core.k8s:
    state: absent
    definition: |
      apiVersion: authentication.open-cluster-management.io/v1beta1
      kind: ManagedServiceAccount
      metadata:
        name: "{{ generated_sa_name }}"
        namespace: "{{ cluster.name }}"
    host: "{{ hub_url }}/local-cluster"
    api_key: "{{ hub_token }}"
    validate_certs: false

- name: Delete ManifestWork - cluster {{ cluster.name }}
  kubernetes.core.k8s:
    state: absent
    definition: |
      apiVersion: work.open-cluster-management.io/v1
      kind: ManifestWork
      metadata:
        name: "{{ generated_sa_name }}"
        namespace: "{{ cluster.name }}"
    host: "{{ hub_url }}/local-cluster"
    api_key: "{{ hub_token }}"
    validate_certs: false
