- name: Create the service account (ManagedServiceAccount) - cluster {{ cluster.name }}
  kubernetes.core.k8s:
    definition: |
      apiVersion: authentication.open-cluster-management.io/v1beta1
      kind: ManagedServiceAccount
      metadata:
        name: {{ generated_sa_name }}
        namespace: "{{ cluster.name }}"
      spec:
        rotation:
          enabled: true
          validity: 8640h0m0s
    host: "{{ hub_url }}/local-cluster"
    api_key: "{{ hub_token }}"
    validate_certs: false

- name: Set RBAC on the service account (ManifestWork) - cluster {{ cluster.name }}
  kubernetes.core.k8s:
    definition: |
      apiVersion: work.open-cluster-management.io/v1
      kind: ManifestWork
      metadata:
        name: {{ generated_sa_name }}
        namespace: "{{ cluster.name }}"
      spec:
        workload:
          manifests:
            - apiVersion: rbac.authorization.k8s.io/v1
              kind: ClusterRoleBinding
              metadata:
                name: cluster-admin-app
              roleRef:
                apiGroup: rbac.authorization.k8s.io
                kind: ClusterRole
                name: cluster-admin
              subjects:
                - kind: ServiceAccount
                  name: {{ generated_sa_name }}
                  namespace: open-cluster-management-agent-addon
    host: "{{ hub_url }}/local-cluster"
    api_key: "{{ hub_token }}"
    validate_certs: false

- name: Retrieve the token - cluster {{ cluster.name }}
  kubernetes.core.k8s_info:
    kind: Secret
    name: "{{ generated_sa_name }}"
    namespace: "{{ cluster.name }}"
    host: "{{ hub_url }}/local-cluster"
    api_key: "{{ hub_token }}"
    validate_certs: false
  register: __sa_token
  until: __sa_token is not failed
  retries: 10
  delay: 15

- name: Save the token - cluster {{ cluster.name }}
  ansible.builtin.set_fact:
    cluster_token_list: "{{ cluster_token_list | default([]) + [__cluster] }}"
  vars:
    __cluster:
      name: "{{ cluster.name }}"
      token: "{{ __sa_token.resources[0].data.token | b64decode }}"
