# Retrieve the list of managed clusters and set the clusters variable.
#
# Each managed cluster has a corresponding namespace labelled
# `cluster.open-cluster-management.io/managedCluster` on the Hub (local-cluster).
#
# We need to exclude the Hub namespace from the list.

- name: Get the list of managed cluster namespaces
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    label_selectors:
      - "cluster.open-cluster-management.io/managedCluster"
    host: "{{ hub_url }}/local-cluster"
    api_key: "{{ hub_token }}"
    validate_certs: false
  register: managed_clusters_namespaces

- name: Save the list of managed clusters, excluding the Hub (local-cluster)
  ansible.builtin.set_fact:
    # Exclude local cluster
    clusters: >
      {{ managed_clusters_namespaces.resources
        | map(attribute='metadata.name')
        | reject('equalto', 'local-cluster')
        | list
      }}
