- name: Set cluster connection vars - cluster {{ cluster.name }}
  ansible.builtin.set_fact:
    __server: "{{ hub_url }}/{{ cluster.name }}"
    __token: "{{ cluster_token_list | selectattr('name', '==', cluster.name) | map(attribute='token') | first }}"

# https://access.redhat.com/support/cases/#/case/04391673
- name: Run SA count per SCC script - cluster {{ cluster.name }}
  ansible.builtin.shell: |
    set -o pipefail

    oc login --token={{ __token }} --server={{ __server }} > /dev/null

    SCC_LIST="restricted privileged restricted-v2 node-exporter nonroot-v2 anyuid hostnetwork nonroot hostnetwork-v2 hostaccess hostmount-anyuid"
    echo "Service Account count per SCC:"
    echo "------------------------------"
    for scc in $SCC_LIST; do
      # Check if the SCC exists on the cluster to avoid errors
      if oc get scc "$scc" >/dev/null 2>&1; then
      # Run 'who-can' with a space between 'scc' and the variable '$scc'
      COUNT=$(oc adm policy who-can use scc "$scc" | grep -o "system:serviceaccount:[^ ]*" | sort -u | wc -l)
      echo "$scc: $COUNT"
    else
      echo "$scc: Not found on this cluster"
    fi
    done
  changed_when: false
  register: __script_output

- name: Print SA count per SCC output - cluster {{ cluster.name }}
  ansible.builtin.debug:
    msg: "{{ __script_output.stdout_lines }}"
